version: '3'
services:
  app:
    container_name: ainterview
    restart: always 
    build: . 
    ports: 
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - Questions.General: